apiVersion: v1
kind: Pod
metadata:
    name: usonic-cli
spec:
    containers:
    - name: cli
      image: docker.io/microsonic/usonic-cli:latest
      imagePullPolicy: IfNotPresent
      command: ['sh', '-c', 'sleep 100000']
      volumeMounts:
      - name: sonic-db-config
        mountPath: /var/run/redis/sonic-db/
      - name: sonic-version
        mountPath: /etc/sonic/
      - name: usonic-config
        mountPath: /etc/usonic/
    volumes:
    - name: sonic-db-config
      configMap:
          name: sonic-db-config
    - name: sonic-version
      configMap:
          name: sonic-version
    - name: usonic-config
      configMap:
          name: usonic-config
