apiVersion: v1
kind: Pod
metadata:
    name: redis
    labels:
        app: redis
spec:
    containers:
    - name: redis
      image: docker.io/microsonic/usonic-debug:201904
      imagePullPolicy: IfNotPresent
      command: ["redis-server", "/etc/redis/redis.conf"]
      volumeMounts:
      - name: redis-sock
        mountPath: /var/run/redis/
      - name: redis-server-config
        mountPath: /etc/redis/
      ports:
      - containerPort: 6379
    volumes:
    - name: redis-sock
      hostPath:
          path: /var/lib/usonic/redis
          type: Directory
    - name: redis-server-config
      configMap:
          name: redis-server-config
